- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: install apache
    apt:
      name: apache2
      update_cache: yes
  - name: apache service
    service:
      name: apache2
      state: started
  - name: deploy html
    copy:
      src: index.html
      dest: /var/www/html/index.html
